spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:data.sql

server:
  port: 8082