spring:
  application:
    name: order
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:50}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
    username: order
    password: order123
    url: jdbc:postgresql://localhost:9082/order

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8082
