test_pod:
  enabled: true
  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent

loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri:
        - match:
            pipeline_name: simple-logger
            selector: '{app="simple-logger"}'
            stages:
              - json:
                  expressions:
                    level: level
                    message: msg
                    time: time
              - labels:
                  level:
              - timestamp:
                  source: time
                  format: RFC3339Nano
              - output:
                  source: message

grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin123
  image:
    tag: 10.1.5
